name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch dependencies
        run: npm install
      - name: Build
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch dependencies
        run: npm install
      - name: Check linting
        run: npm run lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch dependencies
        run: npm install
      - name: Check formatting
        run: npm run format:check

